version: 2

run:
  go: "1.25"
  timeout: 5m

format:
  enable: [gofmt, goimports, gci]

format-settings:
  gci:
    sections: [standard, default, "prefix(github.com/banzaicloud/imps)"]
  goimports:
    local-prefixes: github.com/banzaicloud/imps

linters:
  enable:
    - govet
    - staticcheck        # covers what gosimple used to report
    - errcheck
    - ineffassign
    - unused
    - unparam
    - nilerr
    - errname
    - forcetypeassert
    - prealloc
    - durationcheck
    - copyloopvar        # replaces exportloopref
    - misspell
    - gosec
    - dupl
    - rowserrcheck
    - sqlclosecheck
    - tparallel
    - whitespace
    - gocyclo

  disable:
    - lll
    - gochecknoinits
    - gochecknoglobals
    - goconst
    - funlen
    - gocritic
    - godox
    - wsl
    - gocognit
    - godot
    - nestif
    - testpackage
    - nolintlint
    - wrapcheck
    - varnamelen
    - ireturn
    - exhaustruct
    - gomoddirectives
    - exhaustive
    - cyclop
    - perfsprint
    - mnd
    - depguard
    # - tenv  # removed in v2; keep it out

linters-settings:
  gocyclo:
    min-complexity: 40
  gocritic:
    disabled-checks: [ifElseChain]

issues:
  exclude:
    - underscore in package name
    - should not use underscores in package names
  exclude-rules:
    - linters: [stylecheck]
      text: "ST1016"

  exclude-files:
    - ".*zz_.*\\.go$"
  exclude-dirs:
    - .gen