apiVersion: v1
name: imagepullsecrets
description: Dynamically manage pull secrets for images
home: https://banzaicloud.com

maintainers:
- email: engineering@cloudbees.com
  name: CloudBees Inc.
sources:
- https://github.com/cloudbees-oss/imps

version: 0.3.20
appVersion: 0.3.20
